name: Build Multi-Platform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-cors graphene flask-graphql opencv-python-headless pillow numpy

    - name: Install Node dependencies
      run: npm ci

    - name: Build Python bundle
      run: npm run python-build

    - name: Build React app (Linux/macOS)
      if: matrix.platform != 'windows'
      run: NODE_OPTIONS="--openssl-legacy-provider" npm run react-build

    - name: Build React app (Windows)
      if: matrix.platform == 'windows'
      shell: pwsh
      run: |
        $env:NODE_OPTIONS="--openssl-legacy-provider"
        npm run react-build

    - name: Build Electron main process
      run: npm run --silent main-build

    - name: List build artifacts (Linux/macOS)
      if: matrix.platform != 'windows'
      run: ls -la dist/ || echo "No dist directory"

    - name: List build artifacts (Windows)
      if: matrix.platform == 'windows'
      shell: pwsh
      run: |
        if (Test-Path "dist") {
          Get-ChildItem -Path "dist" -Force
        } else {
          Write-Host "No dist directory"
        }

    - name: Upload Linux artifacts
      if: matrix.platform == 'linux'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          dist/*.AppImage
          dist/*.snap
          dist/*.deb
          dist/*.rpm
        if-no-files-found: warn

    - name: Upload Windows artifacts
      if: matrix.platform == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          dist/*.exe
          dist/*.msi
          dist/*.zip
        if-no-files-found: warn

    - name: Upload macOS artifacts
      if: matrix.platform == 'macos'
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          dist/*.dmg
          dist/*.pkg
          dist/*.zip
        if-no-files-found: warn