name: Build macOS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Node dependencies
      run: npm ci

    - name: Build Python bundle
      run: npm run python-build
      env:
        RETINAFACE_PYTHON: python3.10
        PIP_DISABLE_PIP_VERSION_CHECK: '1'

    - name: Build React app
      run: npx craco build
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"
        CI: false
        GENERATE_SOURCEMAP: false

    - name: Build Electron main process
      run: |
        npx tsc -p tsconfig.electronMain.json
        # Build DMG for both Intel (x64) and Apple Silicon (arm64)
        npx electron-builder --mac dmg --x64 --publish=never
        npx electron-builder --mac dmg --arm64 --publish=never
      env:
        ELECTRON_BUILDER_CACHE: ${{ runner.temp }}/electron-builder-cache
        PYTHON: python3

    - name: List build artifacts
      run: ls -la dist/ || echo "No dist directory"

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
            dist/*.zip
            dist/*.dmg
            dist/*.app
        if-no-files-found: warn